name: debugger v2
on: 
  workflow_dispatch:
jobs:
  merge-develop-to-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge develop into main
      run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff develop -m "Auto-merge develop into master"
          git push
